/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-11-22 18:29:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trangchu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("    <!-- bootstrap css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"main.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- font awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/all.css\" />\r\n");
      out.write("    <title>Đồ án 2</title>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <section id=\"room-info\" class=\"py-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <!-- Bảng trạn thái -->\r\n");
      out.write("        <div class=\"row my-5\">\r\n");
      out.write("          <div class=\"col-8 mx-auto\">\r\n");
      out.write("            <div class=\"card card-body bg-success text-uppercase text-center\">\r\n");
      out.write("              <div class=\"card-title text-white\">\r\n");
      out.write("                <h6>Thông tin căn phòng</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row ml-3\">\r\n");
      out.write("                <p>\r\n");
      out.write("                  Nhiệt độ:\r\n");
      out.write("                  <span id=\"room-temp\" class=\"text-light\">26</span>\r\n");
      out.write("                  <span class=\"text-light\">°C</span>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row ml-3\">\r\n");
      out.write("                <p>\r\n");
      out.write("                  Chế độ:\r\n");
      out.write("                  <span id=\"mode-text\" class=\"text-light\">Manual</span>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row ml-3\">\r\n");
      out.write("                <p>\r\n");
      out.write("                  thời gian mở: \r\n");
      out.write("                  <span id=\"time-on\" class=\"text-light\">00:00</span>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row ml-3\">\r\n");
      out.write("                <p>\r\n");
      out.write("                  thời gian tắt: \r\n");
      out.write("                  <span id=\"time-off\" class=\"text-light\">00:00</span>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row justify-content-center\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger\" data-toggle=\"modal\"  onclick=\"showAlert()\" id=\"settime-btn\">Đặt thời gian</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Kết thúc bảng trạng thái -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal fade\" id=\"basicModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"basicModal\" aria-hidden=\"true\">\r\n");
      out.write("          <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("              <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"myModalLabel\">Thiết lập thời gian</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                  <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"form-group row\">\r\n");
      out.write("                  <label for=\"example-time-input\" class=\"col-2 col-form-label\">Giờ mở</label>\r\n");
      out.write("                  <div class=\"col-10\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"time\" value=\"17:30\" id=\"time-on-input\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group row\">\r\n");
      out.write("                  <label for=\"example-time-input\" class=\"col-2 col-form-label\">Giờ tắt</label>\r\n");
      out.write("                  <div class=\"col-10\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"time\" value=\"22:00\" id=\"time-off-input\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"saveChanges\" onclick=\"saveChanges()\" data-dismiss=\"modal\">Lưu thay đổi</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- Chế độ -->\r\n");
      out.write("          <div class=\"col mx-auto text-center d-flex align-items-center flex-column mb-4\">\r\n");
      out.write("            <div class='text-uppercase text-danger font-weight-bold'>\r\n");
      out.write("              <p>Chế độ</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button \r\n");
      out.write("              class=\"btn btn-primary text-uppercase\" \r\n");
      out.write("              onclick=\"toggleMode()\"\r\n");
      out.write("            >\r\n");
      out.write("              <span id=\"mode-status\" class=\"text-uppercase\">automa</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Kết thúc chế độ -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- Đèn 1 -->\r\n");
      out.write("          <div class=\"col-4 text-center d-flex align-items-center flex-column\">\r\n");
      out.write("            <div class='text-uppercase text-danger font-weight-bold'>\r\n");
      out.write("              <p>Đèn 1</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"bulb-1\" class=\"device mb-3\"></div>\r\n");
      out.write("            <button \r\n");
      out.write("              class=\"btn btn-primary text-uppercase\" \r\n");
      out.write("              onclick=\"toggleStatusBulb_1()\" style=\"visibility: visible\"\r\n");
      out.write("              id = \"btn-den1\"\r\n");
      out.write("            >\r\n");
      out.write("              <span id=\"bulb-1-status\">off</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Kết thúc đèn 1 -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Đèn 2 -->\r\n");
      out.write("          <div class=\"col-4 text-center d-flex align-items-center flex-column\">\r\n");
      out.write("            <div class='text-uppercase text-danger font-weight-bold'>\r\n");
      out.write("              <p>Đèn 2</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"bulb-2\" class=\"device mb-3\"></div>\r\n");
      out.write("            <button \r\n");
      out.write("              class=\"btn btn-primary text-uppercase\" \r\n");
      out.write("              onclick=\"toggleStatusBulb_2()\" id=\"btn-den2\"\r\n");
      out.write("              style=\"visibility: visible\"\r\n");
      out.write("            >\r\n");
      out.write("              <span id=\"bulb-2-status\">off</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Kết thúc đèn 2 -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Quạt -->\r\n");
      out.write("          <div class=\"col-4 text-center d-flex align-items-center flex-column\">\r\n");
      out.write("            <div class='text-uppercase text-danger font-weight-bold'>\r\n");
      out.write("              <p>Quạt</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"fan\" class=\"device mb-3\"></div>\r\n");
      out.write("            <button \r\n");
      out.write("              class=\"btn btn-primary text-uppercase\" \r\n");
      out.write("              onclick=\"toggleStatusFan()\" id = \"btn-quat\"\r\n");
      out.write("              style=\"visibility: visible\"\r\n");
      out.write("            >\r\n");
      out.write("              <span id=\"fan-status\">off</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Kết thúc quạt -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("    <!-- jquery -->\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap js -->\r\n");
      out.write("    <script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"app.js\"></script>\r\n");
      out.write("    }\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
